language: cpp
git:
  submodules: false
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:tobydox/mingw -y
  - sudo add-apt-repository ppa:mingw-packages/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get -y install build-essential zlib1g-dev libc6-dev-i386 
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.9-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq gcc-4.9 g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo wget https://www.archlinux.org/packages/community/any/mingw-w64-winpthreads/download/ -O /pthreads.tar.xz
  - sudo wget https://www.archlinux.org/packages/community/x86_64/mingw-w64-binutils/download/ -O /mingw-w64-binutils.tar.xz
  - sudo wget https://www.archlinux.org/packages/community/any/mingw-w64-crt/download/ -O /mingw-w64-crt.tar.xz
  - sudo wget https://www.archlinux.org/packages/community/x86_64/mingw-w64-gcc/download/ -O /mingw-w64-gcc.tar.xz
  - sudo wget https://www.archlinux.org/packages/community/any/mingw-w64-headers/download/ -O /mingw-w64-headers.tar.xz
  - sudo wget http://servers.piernov.org/~piernov/mingw-w64-zlib-1.2.8-5-any.pkg.tar.xz -O /mingw-w64-zlib.tar.xz
  - pushd / && for i in *.tar.xz; do sudo tar -xvf $i; done
  - popd && ./build_miaoumod_mingw.sh  
script:
  - CROSS="mingw64" ./compile.sh

compiler:
  - clang
  - gcc
